export const foodDatabase = [
  { id: '1', name: 'Abacate', unit_g: 100, calories: 160, carbs: 8.5, fats: 14.7, proteins: 2 },
  { id: '2', name: 'Alho', unit_g: 100, calories: 149, carbs: 33.1, fats: 0.5, proteins: 6.4 },
  { id: '3', name: 'Arroz branco cozido', unit_g: 100, calories: 130, carbs: 28, fats: 0.3, proteins: 2.7 },
  { id: '4', name: 'Atum em lata ao natural', unit_g: 100, calories: 128, carbs: 0, fats: 0.7, proteins: 28 },
  { id: '5', name: 'Aveia em flocos', unit_g: 100, calories: 389, carbs: 66, fats: 6.9, proteins: 16.9 },
  { id: '6', name: 'Avocado', unit_g: 100, calories: 160, carbs: 8.5, fats: 14.7, proteins: 2 },
  { id: '7', name: 'Azeite de oliva', unit_g: 100, calories: 884, carbs: 0, fats: 100, proteins: 0 },
  { id: '8', name: 'Bacon', unit_g: 100, calories: 541, carbs: 1.4, fats: 52, proteins: 37 },
  { id: '9', name: 'Banana', unit_g: 100, calories: 89, carbs: 23, fats: 0.3, proteins: 1.1 },
  { id: '10', name: 'Barra Nutrata Protobar Havanna', unit_g: 70, calories: 280, carbs: 35, fats: 7, proteins: 21 },
  { id: '11', name: 'Batata inglesa cozida', unit_g: 100, calories: 86, carbs: 20, fats: 0.1, proteins: 1.6 },
  { id: '12', name: 'Bolacha de leite maltado', unit_g: 100, calories: 480, carbs: 70, fats: 18, proteins: 6 },
  { id: '13', name: 'Brócolis cozido', unit_g: 100, calories: 35, carbs: 7, fats: 0.4, proteins: 2.4 },
  { id: '14', name: 'Berinjela', unit_g: 100, calories: 25, carbs: 6, fats: 0.2, proteins: 1 },
  { id: '15', name: 'Carne moída', unit_g: 100, calories: 250, carbs: 0, fats: 15, proteins: 26 },
  { id: '16', name: 'Cebola', unit_g: 100, calories: 40, carbs: 9, fats: 0.1, proteins: 1.1 },
  { id: '17', name: 'Zucchini', unit_g: 100, calories: 17, carbs: 3.1, fats: 0.3, proteins: 1.2 },
  { id: '18', name: 'Cerveja', unit_g: 100, calories: 43, carbs: 3.6, fats: 0, proteins: 0.5 },
  { id: '19', name: 'Creme de ricota light', unit_g: 100, calories: 140, carbs: 3, fats: 10, proteins: 10 },
  { id: '20', name: 'Feijão preto cozido', unit_g: 100, calories: 132, carbs: 23, fats: 0.5, proteins: 8.7 },
  { id: '21', name: 'Mamão', unit_g: 100, calories: 43, carbs: 11, fats: 0.3, proteins: 0.5 },
  { id: '22', name: 'Frango (cozido)', unit_g: 100, calories: 165, carbs: 0, fats: 3.6, proteins: 31 },
  { id: '23', name: 'Gelatina diet', unit_g: 100, calories: 10, carbs: 0, fats: 0, proteins: 2 },
  { id: '24', name: 'Granola', unit_g: 100, calories: 471, carbs: 64, fats: 16, proteins: 10 },
  { id: '25', name: 'Hipercalórico Optimum Nutrition', unit_g: 100, calories: 400, carbs: 75, fats: 5, proteins: 25 },
  { id: '26', name: 'Iogurte zero', unit_g: 100, calories: 50, carbs: 5, fats: 0, proteins: 4 },
  { id: '27', name: 'Leite integral', unit_g: 100, calories: 61, carbs: 4.8, fats: 3.3, proteins: 3.2 },
  { id: '28', name: 'Leite sem lactose', unit_g: 100, calories: 61, carbs: 4.8, fats: 3.3, proteins: 3.2 },
  { id: '29', name: 'Maçã', unit_g: 100, calories: 52, carbs: 14, fats: 0.2, proteins: 0.3 },
  { id: '30', name: 'Macarrão cozido', unit_g: 100, calories: 158, carbs: 31, fats: 0.9, proteins: 5.8 },
  { id: '31', name: 'Manteiga', unit_g: 100, calories: 717, carbs: 0.1, fats: 81, proteins: 0.9 },
  { id: '32', name: 'Molho de tomate', unit_g: 100, calories: 32, carbs: 7, fats: 0.2, proteins: 1.5 },
  { id: '33', name: 'Ovo cozido', unit_g: 100, calories: 155, carbs: 1.1, fats: 10.6, proteins: 12.6 },
  { id: '34', name: 'Pão francês', unit_g: 100, calories: 270, carbs: 56, fats: 1.5, proteins: 8.4 },
  { id: '35', name: 'Pão integral', unit_g: 100, calories: 247, carbs: 41, fats: 3.4, proteins: 9.6 },
  { id: '36', name: 'Peito de peru defumado', unit_g: 100, calories: 104, carbs: 0, fats: 1.2, proteins: 22 },
  { id: '37', name: 'Picanha na brasa', unit_g: 100, calories: 250, carbs: 0, fats: 15, proteins: 26 },
  { id: '38', name: 'Queijo cottage sem lactose', unit_g: 100, calories: 98, carbs: 3, fats: 4, proteins: 11 },
  { id: '39', name: 'Queijo mussarela sem lactose', unit_g: 100, calories: 300, carbs: 2, fats: 22, proteins: 22 },
  { id: '40', name: 'Ricota', unit_g: 100, calories: 140, carbs: 3, fats: 10, proteins: 10 },
  { id: '41', name: 'Tapioca', unit_g: 100, calories: 360, carbs: 90, fats: 0, proteins: 0 },
  { id: '42', name: 'Tomate', unit_g: 100, calories: 18, carbs: 3.9, fats: 0.2, proteins: 0.9 },
  { id: '43', name: 'Tomate pelado em lata', unit_g: 100, calories: 32, carbs: 7, fats: 0.2, proteins: 1.5 },
  { id: '44', name: 'Torrada Bauducco integral', unit_g: 100, calories: 380, carbs: 70, fats: 6, proteins: 10 },
  { id: '45', name: 'Tilapia', unit_g: 100, calories: 129, carbs: 0, fats: 2.7, proteins: 26 },
  { id: '46', name: 'Vinho (tinto seco)', unit_g: 100, calories: 83, carbs: 2.6, fats: 0, proteins: 0.1 },
  { id: '47', name: 'Optimum GOLD STANDARD 100% WHEY', unit_g: 100, calories: 396.7, carbs: 9.6, fats: 4.8, proteins: 77.4 },
];

export const recipesDatabase = [
  { id: '1', name: 'Guacamole', desc: 'Abacate, tomate, cebola, azeite' },
  { id: '2', name: 'Sanduíche Peito de Peru', desc: 'Pão integral, peito de peru, ricota' },
  { id: '3', name: 'Frango Desfiado Cozido', desc: 'Frango, bacon, alho, cebola, tomate, azeite, pimentões' },
  { id: '4', name: 'Carne Moída Grelhada', desc: 'Carne moída, alho, cebola, azeite, tomate' },
  { id: '5', name: 'Aveia Overnight', desc: 'Aveia, leite, whey' },
  { id: '6', name: 'Macarrão à Bolonhesa', desc: 'Macarrão integral, carne moída, bacon, cebola, alho, molho tomate' },
  { id: '7', name: 'Peixe Grelhado', desc: 'Peixe, azeite, alho, cebola' },
  { id: '8', name: 'Sanduíche de Ovo', desc: 'Pão, ovo, queijo cottage' },
  { id: '9', name: 'Creme de Peito de Peru', desc: 'Creme ricota, peito peru, alho, azeite' },
  { id: '10', name: 'Lasanha Vegetariana Fit', desc: 'Zucchini, tomate, cottage, azeite, alho, cebola' },
  { id: '11', name: 'Lasanha Bolonhesa Fit', desc: 'Berinjela, carne moída, bacon, molho tomate, azeite, alho' },
  { id: '12', name: 'Strogonoff de Frango', desc: 'Frango, azeite, cebola, alho, molho tomate, creme ricota' },
  { id: '13', name: 'Tapioca Queijo e Peru', desc: 'Tapioca, queijo, peito de peru' },
  { id: '14', name: 'Smoothie Proteico', desc: 'Banana, mamão, avocado, whey, iogurte' },
  { id: '15', name: 'Gelatina Diet c/ Iogurte', desc: 'Gelatina diet, iogurte' },
  { id: '16', name: 'Smoothie Avocado Whey', desc: 'Avocado, iogurte, whey' },
];
